# Generated by Django 5.2.8 on 2025-12-17 17:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='Profiles-images/default_xazwoa', max_length=255, verbose_name='image'),
        ),
    ]
